### ISSUE TITLE
Which branch is main branch?

### ISSUE THREAD

**Issue by ymd-h** [syuntoku14/pytorch-rl-il#2]
Hi!

Thank you for your interesting project.

I have a question.
Which branch is main branch?

*  master: Set as default on GitHub.com but has only 1 initial commit
*  develop: Actively maintained

cf. https://help.github.com/en/github/administering-a-repository/setting-the-default-branch

**Comment by syuntoku14** [comment]
Hello Yamada-san.

Thank you for your advice. 
I changed the default branch from master to develop. 

Currently, I'm working on the develop branch, but I'll merge the develop to master branch after a few updates. I'll change the default branch to master after I merge them.

**Comment by ymd-h** [comment]
Thank you for your quick answer!

I close this issue.
